### ISSUE TITLE
Midterm-jpark.py is ready!

### ISSUE THREAD

**Issue by ipowers-matc** [madisoncollege-it-programs/python-scripting-ipowers-matc#10]
Midterm-jpark.py is ready for grading!

**Comment by cethenmc** [comment]
Thanks for putting in a very solid effort on this part of the midterm.  The first part I analyze is program execution.  When I enter false username and password combos three times, the third failure should only render the magic word clause 25 times.  You keep the single occurrence with the counter firing on that last one (1 pt).  The purpose of white_rabbit_object was to evaluate it as part of your flow logic to prevent you from needing so many breaks, but I will take only 1 of 2 off because you got it working effectively (1 pt).  I really like the way you used the keys function but turned it to a List for a nicer display.  When you carried that philosophy to your list of values it gives the impression that you eliminated hardcoding, but with the list being finite, and your hardcoding of [0], [1], and [2], there is a better mechanism that can be used directory with dictionary.  In fact lines 25-33 could be consolidated into one if statement without hardcoding (1 pt).  Still, really great effort and score:  30/33.
