### ISSUE TITLE
Week 9 is ready for grading!

### ISSUE THREAD

**Issue by ipowers-matc** [madisoncollege-it-programs/python-scripting-ipowers-matc#11]
Chris, thank you again for the extension. The sleep helped a whole bunch (as it always does) and the assignment has been pushed.

**Comment by cethenmc** [comment]
Isaac - I will record 8 of 8 on this one.  However, in the programming world, the return value would be just the number (and not the full formatted string.  When you print from tempconversion.py you can add the special language that you want.  Returns from a library of functions will usually be a straightforward answer.  Plug in 32 you get 0, plug in 212 you get 100, plug in -40 you get -40.

For your own records, you may want to repush a change to GitHub that puts "The converted temperature from...." in the tempconversion.py (calling script) and make f2c.py (function script) return just the number.  Reach out if this doesn't make sense or you need a hand.

**Comment by cethenmc** [comment]
Isaac - I will also add that the tempconversion.py was intended to be run through the "main()" function, which is why the part title looks like this:  "Script 2 - Temp Conversion (**Main**)."  It was not super clear, so I am not deducting points.  However, you may want to consider modifying your tempconversion.py script to run that way, as well.
