### ISSUE TITLE
Midterm-if.py is ready

### ISSUE THREAD

**Issue by ipowers-matc** [madisoncollege-it-programs/python-scripting-ipowers-matc#9]
Midterm-if.py is ready for grading!

**Comment by cethenmc** [comment]
You put a nice creative effort in on this part of the assignment.  I like that you analyzed your data carefully to identify the column structure in the flat file.  Although there are more efficient ways to do this, you used concepts from class and covered your bases well.  I am going to take just on small point off because when you searched for IP Addresses in the file, you did not search for just the IP.  You search for them with the carriage return.  You somewhat had to do it this because you chose a direct comparison method ('==') instead of an 'in' and because you were using the last field.  You could have done a replace on the left side to replace the "\n" with nothing to avoid that (using your method).  Your score is 32/33
